### ISSUE TITLE
Is xarray really a dependency?

### ISSUE THREAD

**Issue by rabernat** [dgilford/pyPI#4]
Congrats on releasing this amazing package!

It looks like xarray is used for the examples, but your package itself (the contents of the `pypi` folder) doesn't ever import xarray.
https://github.com/dgilford/pyPI/search?q=xarray

So technically xarray is not a dependency.

If you were interested in building an xarray compatibility layer in pyPI, it would be pretty straightforward to wrap your functions using `xarray.apply_ufunc`. That way you could send xarray DataArrays directly in and out of pyPI.

We do something similar in our fastjmd95 package, which implements an ocean equation of state using numba: https://github.com/xgcm/fastjmd95/tree/master/fastjmd95

**Comment by dgilford** [comment]
Hi Ryan,
Thank you!

This is a great point. In retrospect, I probably need to adjust how **requirements.txt** is created so that it only references the package folder... not the full set of examples and sample runs.

Daniel Rothenberg suggested the use of `apply_ufunc` in [run_sample.py](https://github.com/dgilford/pyPI/blob/master/run_sample.py), so it is adapted there, but is not a stand-alone tool within the padckage.

I don't know exactly what a "compatibility layer" is (this being my first foray into this kind of project, I'm still learning), but it sounds really useful. Is it basically a go-between function that allows the user to directly pass xarray data in and out of the main function, but within the package itself? A tool like this could be very helpful!

**Comment by rabernat** [comment]
> Is it basically a go-between function that allows the user to directly pass xarray data in and out of the main function, but within the package itself? A tool like this could be very helpful!

Yes exactly. In [this module](https://github.com/xgcm/fastjmd95/blob/master/fastjmd95/jmd95wrapper.py) from fastjmd95, we have just a quick bit of code (in the form of a decorator) that checks whether the user is passing a regular numpy array, a dask array, or an xr.DataArray. For the later two, it does a little something extra to "wrap" the call to the underlying numba function (which operates only on raw numpy arrays).

In your case, this logic would need to be a bit more complex, since you treat the vertical axis specially. But the same basic pattern would still apply.

The benefit for the user is that they never have to "leave" xarray.
